# Generated by Django 5.0.7 on 2026-09-02 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/')),
                ('applied_role', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='candidates__email_188e48_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('role_level', models.CharField(blank=True, choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead / Staff')], max_length=20)),
                ('recent_projects', models.JSONField(blank=True, default=list)),
                ('raw_resume_text', models.TextField(blank=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('parser_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_profile', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'Resume profile',
                'verbose_name_plural': 'Resume profiles',
            },
        ),
    ]
