# Generated by Django 5.0.7 on 2026-09-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='parsing_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], max_length=10),
        ),
    ]
