# Generated by Django 5.0.7 on 2026-09-02 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('countable_violation_count', models.PositiveSmallIntegerField(default=0)),
                ('warning_issued', models.BooleanField(default=False)),
                ('warning_issued_at', models.DateTimeField(blank=True, null=True)),
                ('terminated', models.BooleanField(default=False)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_session', to='interviews.interviewsession')),
            ],
            options={
                'verbose_name': 'Proctoring session',
                'verbose_name_plural': 'Proctoring sessions',
            },
        ),
        migrations.CreateModel(
            name='ProctoringFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(choices=[('tab_switch', 'Tab switched away'), ('window_blur', 'Window lost focus'), ('fullscreen_exit', 'Exited fullscreen'), ('no_face', 'No face detected'), ('multiple_faces', 'Multiple faces detected'), ('gaze_away', 'Gaze directed away from screen'), ('copy_paste', 'Copy/paste attempted'), ('devtools_opened', 'Developer tools opened')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('counted_toward_violation', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('proctoring_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='proctoring.proctoringsession')),
            ],
            options={
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['proctoring_session', 'flag_type'], name='proctoring__proctor_d076fc_idx')],
            },
        ),
    ]
