# Generated by Django 5.0.7 on 2026-09-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringsession',
            name='reference_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proctoringsession',
            name='reference_photo',
            field=models.ImageField(blank=True, null=True, upload_to='proctoring_reference_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='proctoringflag',
            name='flag_type',
            field=models.CharField(choices=[('tab_switch', 'Tab switched away'), ('window_blur', 'Window lost focus'), ('fullscreen_exit', 'Exited fullscreen'), ('no_face', 'No face detected'), ('multiple_faces', 'Multiple faces detected'), ('gaze_away', 'Gaze directed away from screen'), ('copy_paste', 'Copy/paste attempted'), ('devtools_opened', 'Developer tools opened'), ('face_mismatch', 'Face does not match reference photo')], max_length=30),
        ),
    ]
