# Generated by Django 5.0.7 on 2026-09-02 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_description_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('terminated', 'Terminated early')], default='pending', max_length=20)),
                ('max_questions', models.PositiveSmallIntegerField(default=8)),
                ('questions_asked_count', models.PositiveSmallIntegerField(default=0)),
                ('termination_reason', models.CharField(choices=[('none', 'Not terminated'), ('proctoring_violation', 'Repeated proctoring violation'), ('candidate_left', 'Candidate disconnected'), ('technical_error', 'Technical error')], default='none', max_length=30)),
                ('termination_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.FloatField()),
                ('category_scores', models.JSONField(blank=True, default=dict)),
                ('strengths', models.TextField(blank=True)),
                ('concerns', models.TextField(blank=True)),
                ('content_flags', models.JSONField(blank=True, default=list)),
                ('recruiter_visible', models.BooleanField(default=True)),
                ('candidate_visible', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_rating', to='interviews.interviewsession')),
            ],
            options={
                'verbose_name': 'Final rating',
                'verbose_name_plural': 'Final ratings',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('topic_tag', models.CharField(blank=True, max_length=100)),
                ('generation_context', models.JSONField(blank=True, default=dict)),
                ('asked_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript_text', models.TextField(blank=True)),
                ('audio_ref', models.CharField(blank=True, max_length=500)),
                ('analysis_json', models.JSONField(blank=True, default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interviews.question')),
            ],
            options={
                'ordering': ['question__order'],
            },
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['status'], name='interviews__status_b6a4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['candidate', 'status'], name='interviews__candida_edb7a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('session', 'order')},
        ),
    ]
