# Generated by Django 5.0.7 on 2026-09-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewsession_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='termination_reason',
            field=models.CharField(choices=[('none', 'Not terminated'), ('proctoring_violation', 'Repeated proctoring violation'), ('candidate_left', 'Candidate disconnected'), ('candidate_ended', 'Candidate ended interview early'), ('technical_error', 'Technical error')], default='none', max_length=30),
        ),
    ]
